version: '3.1'

services:
  file_downloader:
    environment:
      - "${CONTAINER_JAR_NAME}:${CONTAINER_JAR_NAME}"
      - "${HOST_JAR_PATH}:${HOST_JAR_PATH}"
      - "${CONTAINER_OUTPUT_DIR}:${CONTAINER_OUTPUT_DIR}"
      - "${CONTAINER_INPUT_DIR}:${CONTAINER_INPUT_DIR}"
      - "${URL_FILE_NAME}:${URL_FILE_NAME}"
    build: .
    volumes:
      - "${HOST_OUTPUT_DIR}:${CONTAINER_OUTPUT_DIR}"
      - "${HOST_INPUT_DIR}:${CONTAINER_INPUT_DIR}"